get "/", forward: "/WEB-INF/pages/index.gtpl"
get "/signup", forward: "/WEB-INF/pages/signup.gtpl"
get "/upload", forward: "/WEB-INF/pages/upload.gtpl"
get "/download", forward: "/WEB-INF/pages/download.gtpl"
get "/downloads/anynines.war",  forward: "/WEB-INF/downloads/anynines.war" 
get "/downloads/anynines.zip",  forward: "/WEB-INF/downloads/anynines.zip" 
